site_name: Global Data Plane Documentation
repo_url: https://github.com/global-data-plane/sdtp  # Update as needed
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
strict: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/global-data-plane/sdtp
  favicon: favicon.ico
  # Any other extra variables you want



nav:
  - Home: README.md
  - Overview:
      - Project Overview: overview.md
      - Architecture: architecture.md
      # - Hello SDTP: hello.md
      # - Manifesto: manifesto.md # move to website
  # - Quick Start: hello.md  # Or create a dedicated quickstart.md
  - User Guide:
      - SDML Reference: sdml_reference.md
      - SDQL Reference: sdql_reference.md
      - SDTP Protocol Reference: sdtp_protocol_reference.md
      - SDTP Client: sdtp_client.md
  - Developer/API Reference:
      # - API Overview: architecture.md  # Or a dedicated API index
      - Class Docs (auto-generated): api/index.md
  # - Cookbook & Examples:
    #  - Recipes & FAQ: hello.md  # Or a cookbook.md if you split it
  # - Docs Manifest: sdtp_documentation_plan.md
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
      # - License & Contributing: manifesto.md

# Optional: Plugins for auto API docs, search, etc.
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [".", "src"]
          options:
            docstring_style: google
            merge_init_into_class: true
            show_source: true

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details

# (Optional) Extra configs for logo, favicon, etc.
extra:
#   logo: images/logo.png
  favicon: favicon.ico
